version: '3.8'

services:
  consorcio-neptuno:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: consorcio-neptuno-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.consorcio-neptuno.rule=Host(`tu-dominio.com`)"
      - "traefik.http.routers.consorcio-neptuno.entrypoints=websecure"
      - "traefik.http.routers.consorcio-neptuno.tls.certresolver=letsencrypt"
      - "traefik.http.services.consorcio-neptuno.loadbalancer.server.port=3000"

# Para desarrollo local
  # consorcio-neptuno-dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   container_name: consorcio-neptuno-dev
  #   ports:
  #     - "3001:3000"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #     - /app/.next
  #   environment:
  #     - NODE_ENV=development
  #   profiles:
  #     - dev
